# Generated by Django 4.2.5 on 2023-09-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('desarrollador', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Desarrollador')),
                ('lanzamiento', models.CharField(max_length=10, verbose_name='Año Lanzamiento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria')),
            ],
        ),
    ]
